name: flutter_generic_api_response
description: This project has been built that has been proof of building Generic Api Response with freeze plugin.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  dio: ^4.0.6
  pretty_dio_logger: ^1.2.0-beta-1
  freezed_annotation: ^2.0.1
  json_serializable: ^6.1.6
  freezed: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.10

flutter:
  uses-material-design: true